define(function (require, exports, module) {
    return {
        '/login': {
            title: '登录',
            name: 'login',
            controller: 'login/index.js',
            layout: 'full',
            service: [],
            nav: 'login',
            style: 'login/index.css',
            permission: 'index',
        },
        '/index': {
            title: 'Alpha',
            name: 'index',
            controller: 'index/index',
            layout: 'content',
            service: [],
            nav: 'index',
            style: 'index/index.css',
            permission: 'index',
        },
        '/permission': {
            title: '权限管理',
            name: 'permission',
            controller: 'permission/index.js',
            layout: 'content',
            service: [],
            nav: 'permission',
            style: 'permission/css/zTreeStyle/zTreeStyle.css',
            permission: 'index',
        },
        //---------------用户管理------------------
        //检索用户
        '/user/search': {
            title: '检索用户',
            name: 'user',
            controller: 'user/search/index.js',
            layout: 'content',
            service: ['user'],
            nav: 'user',
            style: 'user/search/index.css',
            permission: 'user.search',
        },
        //新建用户
        '/user/create': {
            title: '创建用户',
            name: 'user',
            controller: 'user/create/index.js',
            layout: 'content',
            service: ['user'],
            nav: 'user',
            style: 'user/create/index.css',
            permission: 'user.create',
        },
        //查看用户详情
        '/user/detail': {
            title: '用户详情',
            name: 'user',
            controller: 'user/detail/index.js',
            layout: 'content',
            service: ['user'],
            nav: 'user',
            style: 'user/detail/index.css',
            permission: 'user.detail',
        },
        //---------------资源管理------------------
        //检索资源
        '/model/search': {
            title: '检索资源',
            name: 'model',
            controller: 'model/search/index.js',
            layout: 'content',
            service: [],
            nav: 'model',
            style: 'model/search/index.css',
            permission: 'model.search',
        },
        //---------------项目管理------------------
        //检索项目
        '/project/search': {
            title: '检索项目',
            name: 'project',
            controller: 'project/search/index.js',
            layout: 'content',
            service: [],
            nav: 'project',
            style: 'project/search/index.css',
            permission: 'project.search',
        },
        '/project/bidding': {
            title: '检索项目',
            name: 'project',
            controller: 'project/bidding/index.js',
            layout: 'content',
            service: [],
            nav: 'project',
            style: 'project/bidding/index.css',
            permission: 'project.bidding',
        },
        //---------------分润管理------------------
        //下载分润管理
        '/income/downloadIncome': {
            title: '下载分润',
            name: 'income',
            controller: 'income/downloadIncome/index.js',
            layout: 'content',
            service: [],
            nav: 'income',
            style: 'income/downloadIncome/index.css',
            permission: 'income.downloadIncome',
        },
        //项目分润管理
        '/income/projectIncome': {
            title: '项目分润',
            name: 'income',
            controller: 'income/projectIncome/index.js',
            layout: 'content',
            service: [],
            nav: 'income',
            style: 'income/projectIncome/index.css',
            permission: 'income.projectIncome',
        },
        //---------------社区管理------------------
        //社区板块管理
        '/forum/topic': {
            title: '板块管理',
            name: 'forum',
            controller: 'forum/topic/index.js',
            layout: 'content',
            service: [],
            nav: 'forum',
            style: 'forum/topic/index.css',
            permission: 'forum.topic',
        },
        //社区帖子管理
        '/forum/post': {
            title: '板块管理',
            name: 'forum',
            controller: 'forum/post/index.js',
            layout: 'content',
            service: [],
            nav: 'forum',
            style: 'forum/post/index.css',
            permission: 'forum.post',
        },
        //---------------合同管理------------------
        '/contract/create': {
            title: '新建合同',
            name: 'contract',
            controller: 'contract/create/index.js',
            layout: 'content',
            service: ['contract'],
            nav: 'contract',
            style: 'contract/create/index.css',
            permission: 'contract.create',
        },
        '/contract/search': {
            title: '检索合同',
            name: 'contract',
            controller: 'contract/search/index.js',
            layout: 'content',
            service: ['contract'],
            nav: 'contract',
            style: 'contract/search/index.css',
            permission: 'contract.search',
        },
        //---------------统计管理------------------
        '/statistics/contractStat': {
            title: '合同统计',
            name: 'statistics',
            controller: 'statistics/contractStat/index.js',
            layout: 'content',
            service: [],
            nav: 'statistics',
            style: 'statistics/contractStat/index.css',
            permission: 'statistics.contractStat',
        },
        '/statistics/incomeStat': {
            title: '收入统计',
            name: 'statistics',
            controller: 'statistics/incomeStat/index.js',
            layout: 'content',
            service: [],
            nav: 'statistics',
            style: 'statistics/incomeStat/index.css',
            permission: 'statistics.incomeStat',
        },
        '/statistics/modelStat': {
            title: '资源统计',
            name: 'statistics',
            controller: 'statistics/modelStat/index.js',
            layout: 'content',
            service: [],
            nav: 'statistics',
            style: 'statistics/modelStat/index.css',
            permission: 'statistics.modelStat',
        },
        '/statistics/projectStat': {
            title: '项目统计',
            name: 'statistics',
            controller: 'statistics/projectStat/index.js',
            layout: 'content',
            service: [],
            nav: 'statistics',
            style: 'statistics/projectStat/index.css',
            permission: 'statistics.projectStat',
        },
        '/statistics/userStat': {
            title: '用户统计',
            name: 'statistics',
            controller: 'statistics/userStat/index.js',
            layout: 'content',
            service: [],
            nav: 'statistics',
            style: 'statistics/userStat/index.css',
            permission: 'statistics.userStat',
        },
        //---------------权限管理------------------
        '/permissionGroup':{
            title: '权限管理',
            name: 'permission',
            controller: 'permissionGroup/index',
            layout: 'content',
            service: [],
            nav: 'permissionGroup',
            style: 'permissionGroup/index.css',
            permission: 'permissionGroup',
        },
        //---------------客服管理------------------
        '/support':{
            title: '客服管理',
            name: 'support',
            controller: 'support/index',
            layout: 'content',
            service: [],
            nav: 'support',
            style: 'support/index.css',
            permission: 'support',
        },

        //TODO:  客服管理!
     
    }
});